remote_theme: daattali/beautiful-jekyll

title: Prometheus Science

author: Chagas Science Consultancy Limited

navbar-links:
  Services: "/#services"
  About Us: "/#aboutus"
  Clients: "/#clients"
  Open-Source: "/#portfolio"
  Contact Us: "/contact"

title-img: /assets/img/attalitech-logo-light.png

site-css: "/assets/css/attalitech.css"

keywords: "open source hardware, open science ,open source hardware,3d printing"

mobile-theme-col: "#0085A1"
navbar-col: "#05172d"
navbar-text-col: "#fff"
navbar-border-col: "#05172d"

social-network-links:
  email: "contact@prometheus-science.com"
  github: amchagas
  twitter: Prometheus_sci
  #calendly: "attalitech/meeting"
  #youtube: "c/daattali?sub_confirmation=1"
  #patreon: DeanAttali

url-pretty: "prometheus-science.com"

footer-img: "/assets/img/footer-bg.png"

#google_analytics: "UA-59820529-1"

timezone: "Europe/London"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      footer-extra: custom_footer.html
      nav-short: true
      share-description: "Prometheus Science is dedicated to the improvement of research and education through open science services and open source hardware tools."
      share-img: "/assets/img/attalitech.png"

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md


plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
